version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing jq..."
      - dnf install -y jq
      - echo "Logging in to Docker Hub..."
      - DOCKERHUB_SECRET=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query SecretString --output text)
      - DOCKERHUB_USER=$(echo $DOCKERHUB_SECRET | jq -r .DOCKERHUB_USERNAME)
      - DOCKERHUB_PASS=$(echo $DOCKERHUB_SECRET | jq -r .DOCKERHUB_TOKEN)
      - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo "Changing to frontend directory..."
      - cd frontend
      - echo "Building frontend image..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing frontend image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG