# finance-dashboard/docker-compose.yml

services:
  db:
    image: postgres:15-alpine
    container_name: finance-db-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # This automatically reads POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD from the root .env file
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build: ./backend
    container_name: finance-backend-prod
    command: /app/entrypoint.sh
    # This environment block reads all necessary variables from the root .env file
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SANDBOX_SECRET=${PLAID_SANDBOX_SECRET}
      - PLAID_ENV=${PLAID_ENV}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: finance-frontend-prod
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: