services:
  db:
    image: postgres:15-alpine
    container_name: finance-db-local
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build: ./backend
    container_name: finance-backend-local
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SANDBOX_SECRET=${PLAID_SANDBOX_SECRET}
      - PLAID_ENV=${PLAID_ENV}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: finance-frontend-local
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: