version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing jq..."
      - dnf install -y jq
  pre_build:
    commands:
      # Login to Docker Hub
      - echo "Logging in to Docker Hub..."
      - aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query SecretString --output text | docker login --username $(jq -r .DOCKERHUB_USERNAME) --password-stdin
      # Login to Amazon ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the backend Docker image...
      - cd backend
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG