# Generated by Django 5.2.1 on 2025-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='institution_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
