# Generated by Django 5.2.1 on 2025-06-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plaiditem_institution_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_transaction_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iso_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('date', models.DateField()),
                ('category', models.JSONField(blank=True, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
